version: '3'
services:
  db:
    image: "postgres"    
    environment:
      - POSTGRES_USER=craglog_admin
      - POSTGRES_PASSWORD=craglog
      - POSTGRES_DB=craglog_db_dev
    volumes:
      - postgresql:/var/lib/postgresql
    ports:
      - '5432:5432'
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
volumes:
  postgresql: