name: BUILD AND DEPLOY CRAGLOG

on:
  push:
    branches:
      - '*'
    tags:        
      - '*'


jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install backend deps (with cache)
        uses: bahmutov/npm-install@v1.7.1
        with:
          install-command: yarn
          working-directory: ./backend
      
      - name: Setup Test Environment
        run: make up

      - name: Test
        run: yarn test
        with:
          install-command: yarn
          working-directory: ./backend